name: "Auto build project and push release"
# 触发工作流的条件
on:
  # 手动触发工作流
  workflow_dispatch: ~

jobs:
  ReleaseBuild:
    # 运行平台
    runs-on: ubuntu-latest
    steps:
      # Pull code
      - name: Checkout
        uses: actions/checkout@v3
      # Setup java environment
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 21
      # 缓存 Maven 依赖
      - name: Cache maven files
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      # 下载前端, 打包
      - name: Run Maven
        run: bash build/build-release.sh
      # 上传构建jar包
      - name: Upload build
        uses: actions/upload-artifact@v4
        with:
          name: WhaleMusic
          path: starter/target/whale-music.jar