name: "tag push auto build project "
# 触发工作流的条件
on:
  push:
    tags:
      - "v*" # Push events to matching v*, i.e. v1.0, v20.15.10

jobs:
  AutoBuildPushRelease:
    # 运行平台
    runs-on: ubuntu-latest
    steps:
      # Pull code
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }} # 拉取与推送的标签相对应的提交
      # Setup java environment
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 21
      # 缓存 Maven 依赖
      - name: Cache maven files
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      # 下载前端, 打包
      - name: Run Maven
        run: bash build/build-tag.sh ${{ github.ref_name }}
      # 上传构建jar包
      - name: Upload build
        uses: actions/upload-artifact@v4
        with:
          name: WhaleMusic
          path: starter/target/whale-music.jar
      # 上传jar包到release
      - name: Upload release asset
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          # 上传的文件路径，可以使用通配符
          files: starter/target/whale-music.jar
          # 已草稿发布release
          draft: true
